export const GET_REPOSITORIES_REQUEST = "GET_REPOSITORIES_REQUEST";
export const GET_REPOSITORIES_FAILED = "GET_REPOSITORIES_FAILED";
export const GET_REPOSITORIES_SUCCESS = "GET_REPOSITORIES_SUCCESS";
export const SAVE_QUERY = "SAVE_QUERY";
export const CACHE_LAST_REPOSITORIES = "CACHE_LAST_REPOSITORIES";
export const SET_CACHED_ITEM = "SET_CACHED_ITEM";
export const SET_FIRST_PAGE = "SET_FIRST_PAGE";

